[tool.poe.tasks.add-editable-hyfi]
shell = """
  poetry remove hyfi
  poetry add --group dev --editable ../hyfi
"""
help = "Add hyfi as an editable dependency"

[tool.poe.tasks.apply-hyfi-template]
cmd = """
  copier --answers-file .copier-hyfi-config.yaml gh:entelecheia/hyfi-template .
"""
use_exec = true
help = "Apply hyfi template"

[tool.poe.tasks.copy-hyfi-config]
shell = """
  poetry add hyfi@latest
  poetry run hyfi cmd=copy_conf copier.dst_path=src/schedio/conf copier.exclude='**/*/about/__init__.yaml' copier.overwrite=True
"""
help = "Copy hyfi conf to src/schedio/conf"

[tool.poe.tasks.install-clip]
shell = """
  poetry run pip install -e git+https://github.com/openai/CLIP.git@b46f5ac7587d2e1862f8b7b1573179d80dcdd620#egg=clip
"""
help = "Install clip"

[tool.poe.tasks.install-torch]
shell = """
  poetry run pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
"""
help = "Install torch 1.13.1, torchvision 0.14.1, torchaudio 0.13.1"
